version: "3.3"

services:
  http:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - "./:/var/www/"
      - "./docker/default.conf:/etc/nginx/conf.d/default.conf"
    networks:
      - internal_network
    depends_on:
      - db
      - app

  db:
    image: mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - internal_network

  app:
    build:
      args:
        user: ibrahim
        uid: 1000
      dockerfile: ./docker/php.Dockerfile
      context: ./
    working_dir: /var/www
    volumes:
      - "./:/var/www/"
      - "./docker/php.ini:/usr/local/etc/php/conf.d/custom.ini"
    networks:
      - internal_network

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
#    environment:
#      - PMA_ARBITRARY=1
    networks:
      - internal_network

networks:
  internal_network:
    driver: bridge
